### ISSUE TITLE
[QUEST] Best way to edit MOTD/thumbnail ?

### ISSUE THREAD

**Issue by papypom** [PugPickles/UnraidCA#8]
The server works great, what is the recommanded way to add a server thumbnail / change the MOTD as there is no direct access to the root folder ?

Thanks !

**Comment by PugPickles** [comment]
Hi, which app do you mean?

P.S. (If you mean that)
YTSync needs a mount folder/root dir where all media are stored. But you can also use another folder and move the data via a small script.

**Comment by PugPickles** [comment]
Do you mean the papermc image?
I will rebuild the image, but it may take a while, I have a lot to do at the moment.

**Comment by papypom** [comment]
Yup, the PaperMC image for Unraid. No worries at the moment, it works great, but indeed, if there is a way to add a MOTD in the parameters, it would be the cherry on top. Thanks !

**Comment by PugPickles** [comment]
Oh now I get it 😅️

If you use unraid you can click on `Show more settings ...`

otherwise you can use variable `motd`


![Bildschirmfoto vom 2022-12-07 15-55-40](https://user-images.githubusercontent.com/108975072/206212834-1aa83ab1-c496-4d90-9260-716fd9c1910b.png)

**Comment by papypom** [comment]
Aaaaand ... It's there. I missed it. Thanks for your quick answers, was totally my fault. The PaperMC server works great, nothing to change :)

**Comment by PugPickles** [comment]
Nice to hear, thx 🧡️
